import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ContextProvider from "./context/context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Home - Real estate",
  description: "Generated by create next app",
  keywords: "Lorem Ipsum"
};

const RootLayout = ({children,}: Readonly<{children: React.ReactNode;}>) => {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ContextProvider>
          <Navbar />
            <main>
              {children}
            </main>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}

export default RootLayout
